'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.5456
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace srvSGAFP
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://192.168.70.4/", ConfigurationName:="srvSGAFP.wsSGAFPSoap")> _
    Public Interface wsSGAFPSoap

        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento codigoArea del espacio de nombres http://192.168.70.4/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://192.168.70.4/ProcesarAsignacionGanador", ReplyAction:="*")> _
        Function ProcesarAsignacionGanador(ByVal request As srvSGAFP.ProcesarAsignacionGanadorRequest) As srvSGAFP.ProcesarAsignacionGanadorResponse

        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento tdr del espacio de nombres http://192.168.70.4/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://192.168.70.4/ProcesarCreacionOrdenCompra", ReplyAction:="*")> _
        Function ProcesarCreacionOrdenCompra(ByVal request As srvSGAFP.ProcesarCreacionOrdenCompraRequest) As srvSGAFP.ProcesarCreacionOrdenCompraResponse

        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento userid del espacio de nombres http://192.168.70.4/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://192.168.70.4/ProcesarQuedanFactura", ReplyAction:="*")> _
        Function ProcesarQuedanFactura(ByVal request As srvSGAFP.ProcesarQuedanFacturaRequest) As srvSGAFP.ProcesarQuedanFacturaResponse

        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento numeroCheque del espacio de nombres http://192.168.70.4/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://192.168.70.4/ProcesarChequeFactura", ReplyAction:="*")> _
        Function ProcesarChequeFactura(ByVal request As srvSGAFP.ProcesarChequeFacturaRequest) As srvSGAFP.ProcesarChequeFacturaResponse
    End Interface

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
    Partial Public Class ProcesarAsignacionGanadorRequest

        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ProcesarAsignacionGanador", [Namespace]:="http://192.168.70.4/", Order:=0)> _
        Public Body As srvSGAFP.ProcesarAsignacionGanadorRequestBody

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal Body As srvSGAFP.ProcesarAsignacionGanadorRequestBody)
            MyBase.New()
            Me.Body = Body
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://192.168.70.4/")> _
    Partial Public Class ProcesarAsignacionGanadorRequestBody

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=0)> _
        Public codigoArea As String

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=1)> _
        Public codigoPrograma As String

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=2)> _
        Public nombrePrograma As String

        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)> _
        Public duracionHoras As Decimal

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=4)> _
        Public nombreProveedor As String

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=5)> _
        Public nitProveedor As String

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=6)> _
        Public codigoDepartamento As String

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=7)> _
        Public codigoMunicipio As String

        <System.Runtime.Serialization.DataMemberAttribute(Order:=8)> _
        Public tipoPersona As Integer

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=9)> _
        Public noDui As String

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=10)> _
        Public noNrc As String

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=11)> _
        Public direccion As String

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=12)> _
        Public email As String

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=13)> _
        Public telefono As String

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=14)> _
        Public fax As String

        <System.Runtime.Serialization.DataMemberAttribute(Order:=15)> _
        Public numeroParticipantes As Integer

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=16)> _
        Public tdr As String

        <System.Runtime.Serialization.DataMemberAttribute(Order:=17)> _
        Public montoAdjudicado As Decimal

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=18)> _
        Public userid As String

        <System.Runtime.Serialization.DataMemberAttribute(Order:=19)> _
        Public correlativoGrupo As Decimal

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New( _
                    ByVal codigoArea As String, _
                    ByVal codigoPrograma As String, _
                    ByVal nombrePrograma As String, _
                    ByVal duracionHoras As Decimal, _
                    ByVal nombreProveedor As String, _
                    ByVal nitProveedor As String, _
                    ByVal codigoDepartamento As String, _
                    ByVal codigoMunicipio As String, _
                    ByVal tipoPersona As Integer, _
                    ByVal noDui As String, _
                    ByVal noNrc As String, _
                    ByVal direccion As String, _
                    ByVal email As String, _
                    ByVal telefono As String, _
                    ByVal fax As String, _
                    ByVal numeroParticipantes As Integer, _
                    ByVal tdr As String, _
                    ByVal montoAdjudicado As Decimal, _
                    ByVal userid As String, _
                    ByVal correlativoGrupo As Decimal)
            MyBase.New()
            Me.codigoArea = codigoArea
            Me.codigoPrograma = codigoPrograma
            Me.nombrePrograma = nombrePrograma
            Me.duracionHoras = duracionHoras
            Me.nombreProveedor = nombreProveedor
            Me.nitProveedor = nitProveedor
            Me.codigoDepartamento = codigoDepartamento
            Me.codigoMunicipio = codigoMunicipio
            Me.tipoPersona = tipoPersona
            Me.noDui = noDui
            Me.noNrc = noNrc
            Me.direccion = direccion
            Me.email = email
            Me.telefono = telefono
            Me.fax = fax
            Me.numeroParticipantes = numeroParticipantes
            Me.tdr = tdr
            Me.montoAdjudicado = montoAdjudicado
            Me.userid = userid
            Me.correlativoGrupo = correlativoGrupo
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
    Partial Public Class ProcesarAsignacionGanadorResponse

        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ProcesarAsignacionGanadorResponse", [Namespace]:="http://192.168.70.4/", Order:=0)> _
        Public Body As srvSGAFP.ProcesarAsignacionGanadorResponseBody

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal Body As srvSGAFP.ProcesarAsignacionGanadorResponseBody)
            MyBase.New()
            Me.Body = Body
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://192.168.70.4/")> _
    Partial Public Class ProcesarAsignacionGanadorResponseBody

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=0)> _
        Public ProcesarAsignacionGanadorResult As String

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal ProcesarAsignacionGanadorResult As String)
            MyBase.New()
            Me.ProcesarAsignacionGanadorResult = ProcesarAsignacionGanadorResult
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
    Partial Public Class ProcesarCreacionOrdenCompraRequest

        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ProcesarCreacionOrdenCompra", [Namespace]:="http://192.168.70.4/", Order:=0)> _
        Public Body As srvSGAFP.ProcesarCreacionOrdenCompraRequestBody

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal Body As srvSGAFP.ProcesarCreacionOrdenCompraRequestBody)
            MyBase.New()
            Me.Body = Body
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://192.168.70.4/")> _
    Partial Public Class ProcesarCreacionOrdenCompraRequestBody

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=0)> _
        Public tdr As String

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=1)> _
        Public nitProveedor As String

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=2)> _
        Public resolucion As String

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=3)> _
        Public userid As String

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal tdr As String, ByVal nitProveedor As String, ByVal resolucion As String, ByVal userid As String)
            MyBase.New()
            Me.tdr = tdr
            Me.nitProveedor = nitProveedor
            Me.resolucion = resolucion
            Me.userid = userid
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
    Partial Public Class ProcesarCreacionOrdenCompraResponse

        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ProcesarCreacionOrdenCompraResponse", [Namespace]:="http://192.168.70.4/", Order:=0)> _
        Public Body As srvSGAFP.ProcesarCreacionOrdenCompraResponseBody

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal Body As srvSGAFP.ProcesarCreacionOrdenCompraResponseBody)
            MyBase.New()
            Me.Body = Body
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://192.168.70.4/")> _
    Partial Public Class ProcesarCreacionOrdenCompraResponseBody

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=0)> _
        Public ProcesarCreacionOrdenCompraResult As String

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal ProcesarCreacionOrdenCompraResult As String)
            MyBase.New()
            Me.ProcesarCreacionOrdenCompraResult = ProcesarCreacionOrdenCompraResult
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
    Partial Public Class ProcesarQuedanFacturaRequest

        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ProcesarQuedanFactura", [Namespace]:="http://192.168.70.4/", Order:=0)> _
        Public Body As srvSGAFP.ProcesarQuedanFacturaRequestBody

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal Body As srvSGAFP.ProcesarQuedanFacturaRequestBody)
            MyBase.New()
            Me.Body = Body
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://192.168.70.4/")> _
    Partial Public Class ProcesarQuedanFacturaRequestBody

        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)> _
        Public idFacturaAF As Decimal

        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)> _
        Public numeroQuedan As Decimal

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=2)> _
        Public userid As String

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal idFacturaAF As Decimal, ByVal numeroQuedan As Decimal, ByVal userid As String)
            MyBase.New()
            Me.idFacturaAF = idFacturaAF
            Me.numeroQuedan = numeroQuedan
            Me.userid = userid
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
    Partial Public Class ProcesarQuedanFacturaResponse

        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ProcesarQuedanFacturaResponse", [Namespace]:="http://192.168.70.4/", Order:=0)> _
        Public Body As srvSGAFP.ProcesarQuedanFacturaResponseBody

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal Body As srvSGAFP.ProcesarQuedanFacturaResponseBody)
            MyBase.New()
            Me.Body = Body
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://192.168.70.4/")> _
    Partial Public Class ProcesarQuedanFacturaResponseBody

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=0)> _
        Public ProcesarQuedanFacturaResult As String

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal ProcesarQuedanFacturaResult As String)
            MyBase.New()
            Me.ProcesarQuedanFacturaResult = ProcesarQuedanFacturaResult
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
    Partial Public Class ProcesarChequeFacturaRequest

        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ProcesarChequeFactura", [Namespace]:="http://192.168.70.4/", Order:=0)> _
        Public Body As srvSGAFP.ProcesarChequeFacturaRequestBody

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal Body As srvSGAFP.ProcesarChequeFacturaRequestBody)
            MyBase.New()
            Me.Body = Body
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://192.168.70.4/")> _
    Partial Public Class ProcesarChequeFacturaRequestBody

        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)> _
        Public idFacturaAF As Decimal

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=1)> _
        Public numeroCheque As String

        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)> _
        Public fechaEmision As Date

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=3)> _
        Public userid As String

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal idFacturaAF As Decimal, ByVal numeroCheque As String, ByVal fechaEmision As Date, ByVal userid As String)
            MyBase.New()
            Me.idFacturaAF = idFacturaAF
            Me.numeroCheque = numeroCheque
            Me.fechaEmision = fechaEmision
            Me.userid = userid
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
    Partial Public Class ProcesarChequeFacturaResponse

        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ProcesarChequeFacturaResponse", [Namespace]:="http://192.168.70.4/", Order:=0)> _
        Public Body As srvSGAFP.ProcesarChequeFacturaResponseBody

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal Body As srvSGAFP.ProcesarChequeFacturaResponseBody)
            MyBase.New()
            Me.Body = Body
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://192.168.70.4/")> _
    Partial Public Class ProcesarChequeFacturaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ProcesarChequeFacturaResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ProcesarChequeFacturaResult As String)
            MyBase.New
            Me.ProcesarChequeFacturaResult = ProcesarChequeFacturaResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface wsSGAFPSoapChannel
        Inherits srvSGAFP.wsSGAFPSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class wsSGAFPSoapClient
        Inherits System.ServiceModel.ClientBase(Of srvSGAFP.wsSGAFPSoap)
        Implements srvSGAFP.wsSGAFPSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function srvSGAFP_wsSGAFPSoap_ProcesarAsignacionGanador(ByVal request As srvSGAFP.ProcesarAsignacionGanadorRequest) As srvSGAFP.ProcesarAsignacionGanadorResponse Implements srvSGAFP.wsSGAFPSoap.ProcesarAsignacionGanador
            Return MyBase.Channel.ProcesarAsignacionGanador(request)
        End Function
        
        Public Function ProcesarAsignacionGanador( _
                    ByVal codigoArea As String,  _
                    ByVal codigoPrograma As String,  _
                    ByVal nombrePrograma As String,  _
                    ByVal duracionHoras As Decimal,  _
                    ByVal nombreProveedor As String,  _
                    ByVal nitProveedor As String,  _
                    ByVal codigoDepartamento As String,  _
                    ByVal codigoMunicipio As String,  _
                    ByVal tipoPersona As Integer,  _
                    ByVal noDui As String,  _
                    ByVal noNrc As String,  _
                    ByVal direccion As String,  _
                    ByVal email As String,  _
                    ByVal telefono As String,  _
                    ByVal fax As String,  _
                    ByVal numeroParticipantes As Integer,  _
                    ByVal tdr As String,  _
                    ByVal montoAdjudicado As Decimal,  _
                    ByVal userid As String,  _
                    ByVal correlativoGrupo As Decimal) As String
            Dim inValue As srvSGAFP.ProcesarAsignacionGanadorRequest = New srvSGAFP.ProcesarAsignacionGanadorRequest
            inValue.Body = New srvSGAFP.ProcesarAsignacionGanadorRequestBody
            inValue.Body.codigoArea = codigoArea
            inValue.Body.codigoPrograma = codigoPrograma
            inValue.Body.nombrePrograma = nombrePrograma
            inValue.Body.duracionHoras = duracionHoras
            inValue.Body.nombreProveedor = nombreProveedor
            inValue.Body.nitProveedor = nitProveedor
            inValue.Body.codigoDepartamento = codigoDepartamento
            inValue.Body.codigoMunicipio = codigoMunicipio
            inValue.Body.tipoPersona = tipoPersona
            inValue.Body.noDui = noDui
            inValue.Body.noNrc = noNrc
            inValue.Body.direccion = direccion
            inValue.Body.email = email
            inValue.Body.telefono = telefono
            inValue.Body.fax = fax
            inValue.Body.numeroParticipantes = numeroParticipantes
            inValue.Body.tdr = tdr
            inValue.Body.montoAdjudicado = montoAdjudicado
            inValue.Body.userid = userid
            inValue.Body.correlativoGrupo = correlativoGrupo
            Dim retVal As srvSGAFP.ProcesarAsignacionGanadorResponse = CType(Me,srvSGAFP.wsSGAFPSoap).ProcesarAsignacionGanador(inValue)
            Return retVal.Body.ProcesarAsignacionGanadorResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function srvSGAFP_wsSGAFPSoap_ProcesarCreacionOrdenCompra(ByVal request As srvSGAFP.ProcesarCreacionOrdenCompraRequest) As srvSGAFP.ProcesarCreacionOrdenCompraResponse Implements srvSGAFP.wsSGAFPSoap.ProcesarCreacionOrdenCompra
            Return MyBase.Channel.ProcesarCreacionOrdenCompra(request)
        End Function
        
        Public Function ProcesarCreacionOrdenCompra(ByVal tdr As String, ByVal nitProveedor As String, ByVal resolucion As String, ByVal userid As String) As String
            Dim inValue As srvSGAFP.ProcesarCreacionOrdenCompraRequest = New srvSGAFP.ProcesarCreacionOrdenCompraRequest
            inValue.Body = New srvSGAFP.ProcesarCreacionOrdenCompraRequestBody
            inValue.Body.tdr = tdr
            inValue.Body.nitProveedor = nitProveedor
            inValue.Body.resolucion = resolucion
            inValue.Body.userid = userid
            Dim retVal As srvSGAFP.ProcesarCreacionOrdenCompraResponse = CType(Me,srvSGAFP.wsSGAFPSoap).ProcesarCreacionOrdenCompra(inValue)
            Return retVal.Body.ProcesarCreacionOrdenCompraResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function srvSGAFP_wsSGAFPSoap_ProcesarQuedanFactura(ByVal request As srvSGAFP.ProcesarQuedanFacturaRequest) As srvSGAFP.ProcesarQuedanFacturaResponse Implements srvSGAFP.wsSGAFPSoap.ProcesarQuedanFactura
            Return MyBase.Channel.ProcesarQuedanFactura(request)
        End Function
        
        Public Function ProcesarQuedanFactura(ByVal idFacturaAF As Decimal, ByVal numeroQuedan As Decimal, ByVal userid As String) As String
            Dim inValue As srvSGAFP.ProcesarQuedanFacturaRequest = New srvSGAFP.ProcesarQuedanFacturaRequest
            inValue.Body = New srvSGAFP.ProcesarQuedanFacturaRequestBody
            inValue.Body.idFacturaAF = idFacturaAF
            inValue.Body.numeroQuedan = numeroQuedan
            inValue.Body.userid = userid
            Dim retVal As srvSGAFP.ProcesarQuedanFacturaResponse = CType(Me,srvSGAFP.wsSGAFPSoap).ProcesarQuedanFactura(inValue)
            Return retVal.Body.ProcesarQuedanFacturaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function srvSGAFP_wsSGAFPSoap_ProcesarChequeFactura(ByVal request As srvSGAFP.ProcesarChequeFacturaRequest) As srvSGAFP.ProcesarChequeFacturaResponse Implements srvSGAFP.wsSGAFPSoap.ProcesarChequeFactura
            Return MyBase.Channel.ProcesarChequeFactura(request)
        End Function
        
        Public Function ProcesarChequeFactura(ByVal idFacturaAF As Decimal, ByVal numeroCheque As String, ByVal fechaEmision As Date, ByVal userid As String) As String
            Dim inValue As srvSGAFP.ProcesarChequeFacturaRequest = New srvSGAFP.ProcesarChequeFacturaRequest
            inValue.Body = New srvSGAFP.ProcesarChequeFacturaRequestBody
            inValue.Body.idFacturaAF = idFacturaAF
            inValue.Body.numeroCheque = numeroCheque
            inValue.Body.fechaEmision = fechaEmision
            inValue.Body.userid = userid
            Dim retVal As srvSGAFP.ProcesarChequeFacturaResponse = CType(Me,srvSGAFP.wsSGAFPSoap).ProcesarChequeFactura(inValue)
            Return retVal.Body.ProcesarChequeFacturaResult
        End Function
    End Class
End Namespace
