Imports SGAFP.EL
Public Class ucBuscarCENTRO_RESPONSABILIDAD_UNIDAD

    Public Event Seleccionado(ByVal ID_CENTRO_RESPONSABILIDAD As Decimal, ByVal ID_UNIDAD_ORGANIZATIVA As Decimal) 

    Protected Overrides Sub Buscar()
        Dim listaCENTRO_RESPONSABILIDAD_UNIDAD1 As New listaCENTRO_RESPONSABILIDAD_UNIDAD
        listaCENTRO_RESPONSABILIDAD_UNIDAD1 = CType((New cCENTRO_RESPONSABILIDAD_UNIDAD).ObtenerListaPorBusqueda(New CENTRO_RESPONSABILIDAD_UNIDAD, Me.CriteriaList.ToArray()), listaCENTRO_RESPONSABILIDAD_UNIDAD)
        Me.UcListaCENTRO_RESPONSABILIDAD_UNIDAD1.CargarDatosPorLista(listaCENTRO_RESPONSABILIDAD_UNIDAD1)
    End Sub

    Private Sub UcListaCENTRO_RESPONSABILIDAD_UNIDAD1_Seleccionado(ByVal ID_CENTRO_RESPONSABILIDAD As Decimal, ByVal ID_UNIDAD_ORGANIZATIVA As Decimal) Handles UcListaCENTRO_RESPONSABILIDAD_UNIDAD1.Seleccionado
        RaiseEvent Seleccionado(ID_CENTRO_RESPONSABILIDAD, ID_UNIDAD_ORGANIZATIVA)
    End Sub

End Class
